#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
#

ARG sdk_vsn=1.0.1

FROM digitalasset/daml-sdk:${sdk_vsn} AS source

WORKDIR /home/daml/

COPY daml.yaml .
COPY src/main/daml ./src/main/daml

FROM source

EXPOSE 6865
EXPOSE 7500

ENTRYPOINT ~/.daml/bin/daml start \
  --sandbox-option="--address=0.0.0.0" \
  --sandbox-port 6865 \
# Cannot explicitly specify, because of a `daml start` bug.
# Relying on default port behaviour as of now.
#  --navigator-option="--port=7500" \
  --open-browser=no \
  --json-api-port=none
